%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/richasingh/Desktop/Term2/NeuralNetwork/winequality-whitered.csv
%
% Auto-generated by MATLAB on 14-Mar-2020 21:42:14

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["fixedacidity", "volatileacidity", "citricacid", "residualsugar", "chlorides", "freesulfurdioxide", "totalsulfurdioxide", "density", "pH", "sulphates", "alcohol", "quality"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
wine_dataset= readtable("/Users/richasingh/Desktop/Term2/NeuralNetwork/winequality-whitered.csv", opts);

wine_dataset1= readtable("/Users/richasingh/Desktop/Term2/NeuralNetwork/winequality-red.csv", opts);
wine_dataset2= readtable("/Users/richasingh/Desktop/Term2/NeuralNetwork/winequality-white.csv", opts);

final_wine = [wine_dataset1;wine_dataset2]

whos final_wine

%% Clear temporary variables
clear opts

% binary classification problems
X = wine_dataset(:,:);

Y = wine_dataset(:,12);

FF = table2cell(X)
Xt = FF'

%divide the dataset in training and test set at the ratio of 70:30
[m,n] = size(wine_dataset) ;
P = 0.7 ;
idx = randperm(m)  ;
Training = wine_dataset(idx(1:round(P*m)),:) ; 
Testing = wine_dataset(idx(round(P*m)+1:end),:) ;


classes = wine_dataset(:,12);
classes = table2array(classes);
class_labels=categorical(classes(:,1));
tabulate(class_labels)

%define the hypermeter
learningrate = [0.1,0.5,0.7];
Momentum =[0.3,0.6,0.9];
NumberofhiddenSizes = [0,10,20,30,40,50,60,70,80,90,100]

%preparing validation set out of trainig set using cv partition
c = cvpartition(n,'HoldOut',10)

% defining Inputs and Target
inputs = wine_dataset;
targets = 'Quality';

% Create a Pattern Recognition Network
trainFcn = 'trainbr';
performFcn = 'crossentropy'
hiddenSizes =8;
patterennet = hiddenSizes,trainFcn,performFcn;
net = patterennet(hiddenSizes,trainFcn,performFcn)
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'sample';  % Divide up every sample
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;
net.performFcn = 'crossentropy';  
net.trainParam.max_fail=6;

