%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \C:\Users\dell\Desktop\Logistic regression\Logistic\Richa\cancer (1).csv
%
% Auto-generated by MATLAB on 14-Nov-2019 16:48:01

%% Setup the Import Options and import the data
%opts = delimitedTextImportOptions("NumVariables", 32);

% Specify range and delimiter
%opts.DataLines = [1, Inf];
%opts.Delimiter = ",";

% Specify column names and types
%opts.VariableNames = ["VarName1", "M", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"];
%opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
%opts.ExtraColumnsRule = "ignore";
%opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, "M", "EmptyFieldRule", "auto");

% Import the data
%cancer = readtable("/Users/richasingh/Desktop/ML assigmnmet/cancer.csv", opts);


%% Clear temporary variables
%clear opts
%loading the data
data=readtable('cancer.csv');
 
%adding the column names
colNames={'ID','Class','Mean_Radius','Mean_Texture','Mean_Perimeter','Mean_Area',...
    'Mean_Smoothness','Mean_Compactness','Mean_Concavity','Mean_ConcavePts',...
    'Mean_Symmetry','Mean_FractalDim','SE_Radius','SE_Texture','SE_Perimeter',...
    'SE_Area','SE_Smoothness','SE_Compactness','SE_Concavity','SE_ConcavePts',...
    'SE_Symmetry','SE_FractalDim','Worst_Radius','Worst_Texture','Worst_Perimeter', ...
    'Worst_Area','Worst_Smoothness','Worst_Compactness','Worst_Concavity',...
    'Worst_ConcavePts','Worst_Symmetry','Worst_FractalDim'};
 
data.Properties.VariableNames = colNames;
 
%removing of redundant variable ID as not informative for predictive model 
data = removevars(data, 'ID');
 
%printing the data
data(1:5,:);

 
%dividing into training and testing dataset
[m,n] = size(data) ;
P = 0.7 ;
idx = randperm(m)  ;
Training = data(idx(1:round(P*m)),:) ; 
Testing = data(idx(round(P*m)+1:end),:) ;

classes = data(:,1);
classes = table2array(classes);
class_labels=categorical(classes(:,1));
tabulate(class_labels)
 
data2=cell2mat(data{:,1});
class_M=data(data2=='M',:);
class_B=data(data2=='B',:);

%calculating mean_radius and mean_texture
radius_mean_M = mean(class_M.Mean_Radius,1);
texture_mean_M = mean(class_M.Mean_Texture,1);
radius_mean_B = mean(class_B.Mean_Radius,1);
texture_mean_B = mean(class_B.Mean_Texture,1);
area_mean_B = mean(class_B.Mean_Area,1);
area_mean_M = mean(class_M.Mean_Area,1);
 
%calculating Std.deviation of mean_radius and mean|_texture
radius_std_M=std(class_M.Mean_Radius,1);
texture_std_M = std(class_M.Mean_Texture,1);
radius_std_B = std(class_B.Mean_Radius,1);
texture_std_B = std(class_B.Mean_Texture,1);
area_std_B = std(class_B.Mean_Area,1);
area_std_B = std(class_B.Mean_Area,1);

%calculating skewness of mean_radius and mean_texture
radius_skew_M=skewness(class_M.Mean_Radius,1);
texture_skew_M = skewness(class_M.Mean_Texture,1)
radius_skew_B = skewness(class_B.Mean_Radius,1);
texture_skew_B = skewness(class_B.Mean_Texture,1)
area_skew_B = skewness(class_B.Mean_Area,1);
area_skew_B = skewness(class_B.Mean_Area,1);
 
 
figure('Name','Histogram of Mean Radius')
h1=histogram(class_M.Mean_Radius);
hold on
h2=histogram(class_B.Mean_Radius);
legend('Malignant','Benign')
xlabel('Mean Radius of Cell Nuclei')
ylabel('Count')
 
figure('Name','Histogram of Mean Texture')
h3=histogram(class_M.Mean_Texture)
hold on
h4=histogram(class_B.Mean_Texture);
legend('Malignant','Benign')
xlabel('Mean Texture of Cell Nuclei')
ylabel('Count')
 
figure('Name','Histogram eaof Mean Area')
h5=histogram(class_M.Mean_Area);
hold on
h6=histogram(class_B.Mean_Area);
legend('Malignant','Benign')
xlabel('Mean Area of Cell Nuclei')
ylabel('Count')

rng(1);
 
%NumTrees =   
%samples_per_node = 
%depth of tree 
%features in bagv
 
%array with values of number of trees for the forrest 
numTree = [1, 10 , 20 , 30, 40, 50, 60,70, 80, 90, 100] ; 
 
%array of values to try for minimum number of observations per tree leaf
minLeaf = [1:15]; 
 
%array of values to vary the number of predictors to select per split 
numPredictors = [1 :20] ; 
 
%initalize arrays to hold values created in loops 
Parameters = [];
Errors = [] ;  
Final = table ; 
Accuracy = [] ; 
ErrorAllTable = [] ; 
 
%generate list of class labels to use for confusion matrix 
labels_training = table2cell(Training(:,1)); 
labels_testing = Testing{:, 1} ; 
 
for i = 1:length(numTree)
    
    for j = 1:length(minLeaf)
    
        for k = 1:length(numPredictors)
        
        Model = TreeBagger(numTree(i), Training, 'Class', 'OOBPrediction', 'on', 'minLeafSize', minLeaf(j), ...
            'NumPredictorsToSample', numPredictors(k)); 
       
        Parameters = [Parameters; numTree(i), minLeaf(j), numPredictors(k)]; %input the parameters tested into an array
        
        %generate the error (or the misclassification probability) for each
        %model for out-of-bag observations in the training data 
        %using ensemble to calculate an average for all the trees in that
        %model
        model_error = oobError(Model, 'Mode', 'Ensemble') ; 
        
        Error_all = oobError(Model); %generate the errors for each of the trees in the model for plotting
      
        %input the oobError values into an array
        Errors = [Errors; model_error];
        
        ErrorAllTable = [ErrorAllTable ; Error_all];
        
       %use the trained model to predict classes on the out of bag
       %observations stored in the model
       [predicted_labels,scores]= oobPredict(Model);
       
       %generate the confusion matrix from the ooBPredict output 
       CM_model= confusionmat(labels_training,predicted_labels);
        
       %calculate the accuracy of the model using the confusion matrix 
       Accuracy_model = 100*sum(diag(CM_model))./sum(CM_model(:));
       
       %store the model accuracy values in an array
       Accuracy = [Accuracy; Accuracy_model] ; 
       
       %join the parameters test and the model error and accuracy in a row
       %in an array 
       Final = [Parameters Errors Accuracy] ; 
    end
     end 
end 
 
%plot the out of bag classification error for the number of trees grown
figure;
plot(Error_all)
xlabel 'Number of grown trees';
ylabel 'Out-of-bag classification error';
 
%transform the array to a table
Final = array2table(Final) ; 
%assign column names to table
Final.Properties.VariableNames = {'NumTrees', 'NumLeaves' , 'NumSamples', 'oobErrorValue', 'AccuracyValue'} ; 
 
%find the minimum model error
min_error = min(Final{:,4}) %find the minimum error for all the models 
 
%find the highest model accuracy 
highestAccuracy = max(Final{:,5})
 
%find the model row with the highest accuracy and what its parameters are 
best_model = Final(Final.AccuracyValue == highestAccuracy, :)
 
%Train a new model using the parameters 
numtrees = best_model{:,1} ; 
numLeaves = best_model{:,2};
numSamples = best_model{:,3} ; 
Model_Final = TreeBagger(numtrees, Training, 'Class', 'OOBPrediction', 'on', 'minLeafSize', numLeaves, 'NumPredictorsToSample', numSamples); 
 
%Test the model using predict and the testing dataset 
[predicted_labels,scores]= predict(Model_Final, Testing(:, 2:31));
 
%generate a confusion matrix 
CM_model_final= confusionmat(labels_testing,predicted_labels, 'Order', {'M', 'B'});
figure
confusionchart(CM_model_final)
       
%output metrics 
Accuracy_Final = 100*sum(diag(CM_model_final))./sum(CM_model_final(:)) ; 
Error_Final =  oobError(Model_Final, 'Mode', 'Ensemble') ; 
 
%Make the ROC curve
MPosition = find(strcmp('M',Model_Final.ClassNames)) ; %find the column which the malignant cases are in 
 
[false_positives,true_positive,T,AUC] = perfcurve(labels_testing,scores(:,MPosition),'M'); %generate the values
 
%plot ROC curve
figure
plot(false_positives,true_positive)
xlabel('False Positive Rate')
ylabel('True Positive Rate')
AUC %print the area under the curve value 
